name: lint_master

on:
  push:
    branches:
    - master
    - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: install go
      uses: actions/setup-go@v2

    - name: install golangci-lint
      run: |
        set -euo pipefail
        lint_version="$(curl -s -o /dev/null -w '%{redirect_url}' 'https://github.com/golangci/golangci-lint/releases/latest' | sed 's/.*releases\/tag\///g')"
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b "$GITHUB_WORKSPACE" "$lint_version"
    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run -c .golangci.yml ./...
